module "chapter_301". task: 1. Crud servlet, Web app architecture. [#2512];
TODO:

- fix tomorrow: public List <User> getAllUsers () {}

because...

org.postgresql.util.PSQLException: ResultSet not positioned properly, perhaps you need to call next.